name: Publish snapshot package to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish-snapshot:

    runs-on: ubuntu-latest
    if: ${{ contains($(git branch -a --merged), 'teeest') }}
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Remove old packages
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'com.jkwiatko.admin-app-backend'
          ignore-versions: '.*(?<!-SNAPSHOT)$'

      - name: Publish new package
        run: mvn --batch-mode -DuseGitHubPackages deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}