name: Publish snapshot package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish-snapshot:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Remove old packages
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'com.jkwiatko.admin-app-backend'
          ignore-versions: '.*(?<!-SNAPSHOT)$'

      - name: Publish new package
        run: mvn --batch-mode -DuseGitHubPackages -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}