name: publish relese

on:
  workflow_dispatch:

jobs:
  publish-relese:

    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    timeout-minutes: 50
    permissions:
      contents: write

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"

    steps:
      - name: Configure git config
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'release-bot@users.noreply.github.com'

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test and package release
        run: |
          mvn -B -U -DremoveSnapshot validate
          mvn -B package
          artifact=$(echo '${project.name}-${project.version}' | mvn -N -q -DforceStdout help:evaluate)
          echo "target/$artifact.jar" | xargs md5sum > "target/$artifact.md5"
          echo 'release_version=v${project.version}' | { mvn -N -q -DforceStdout help:evaluate; echo " " } >> $GITHUB_ENV
          echo -e "artifact_name=$artifact" >> $GITHUB_ENV

      - name: Create release branch & tag
        env:
          version: ${{ env.release_version }}
        run: |
          git add pom.xml
          git commit -m "Release: Update pom version to $version"
          git checkout -b "release_$version"
          git push origin "release_$version"
          echo "tag_target=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Prepare release notes
        run: |
          echo "# What's Changed:" > action-release-notes.txt
          echo "- Add release changelist here..." >> action-release-notes.txt
          echo "# Notes:" >> action-release-notes.txt
          echo "Source code attachments are left empty intentionally to avoid accidental leaks." >> action-release-notes.txt
          echo "Unfortunately, GitHub doesn't provide the possibility to remove them just yet." >> action-release-notes.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          artifact_name: ${{ env.artifact_name }}
        with:
          tag_name: ${{ env.release_version }}
          target_commitish: ${{ env.tag_target }}
          fail_on_unmatched_files: true
          body_path: action-release-notes.txt
          files: |
            ${{ join(env.artifact_name, '.jar') }}
            ${{ join(env.artifact_name, '.md5') }}

      - name: Prepare for upcoming development
        run: |
          git checkout main
          mvn clean
          mvn -B -DbumpMinor validate
          mvn -B test
          git add pom.xml
          git commit -m "Prepare next development version"

      - name: Log changes
        run : |
          git log > log.txt
          cat log.txt
          cat pom.xml
          git checkout -
          git log > log.txt
          cat log.txt
          cat pom.xml