name: Publish relese package to GitHub Packages

on:
  release:

jobs:
  publish-relese:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test and package
        run: mvn --batch-mode --update-snapshots package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
          body: siemanko


