name: Test on PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set upt LibreOffice
      run: apt-add-repository ppa:libreoffice/ppa && \
           apt update \
           apt upgrade \
           apt install libreoffice \

     - name: checkout branch
     uses: actions/checkout@v3
     with:
       ref: main

    - name: Do virtual merge
      run: git fetch origin ${{ github.head_ref }} && git merge origin/${{ github.head_ref }}

    - name: Validate virtual merge
      run: cat ./pom.xml && which libreoffice

    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots verify
