name: Test on PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"

    env:
      branch: ${{ git branch --show-current }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Do virtual merge
      run: git checkout main && git merge $MERGED
    - name: Validate virtual merge
      run: cat ./pom.xml
    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots verify
