name: Test on PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"

    steps:
    - name: checkout branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install LibreOffice
      run: >
        sudo apt-add-repository ppa:libreoffice/ppa && 
        sudo apt update && 
        sudo apt upgrade && 
        sudo apt install libreoffice

    - name: Do virtual merge
      run: git fetch origin ${{ github.head_ref }} && git merge origin/${{ github.head_ref }}

    - name: Validate virtual merge
      run: > 
      which libreoffice
      echo ${{TEST_TEST}}

    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots verify
